version: '3'
services:
  web-server:
    container_name: blog
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      BLOG_DATABASE_HOSTNAME: blog_postgres
      BLOG_DATABASE_USERNAME: ${DB_USERNAME}
      BLOG_DATABASE_PASSWORD: ${DB_PASSWORD}
    command: ["./wait-for-it.sh", "blog_postgres:5432", "--", "sh", "/go/bin/blog"]
    restart: always
  postgres:
    container_name: blog_postgres
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
