version: '3'
services:
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: blog-development
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
  web-server:
    build: .
    ports:
      - "8080:8080"