version: '3'
services:
  web-server:
    container_name: blog
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      BLOG_DB_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@blog_postgres:5432/${DB_NAME}?sslmode=disable
    command: ["./wait-for-it.sh", "blog_postgres:5432", "--", "./blog"]
    restart: always
  postgres:
    container_name: blog_postgres
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
